
package com.dev.cna;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Identidade", targetNamespace = "https://www5.oab.org.br/integracao/", wsdlLocation = "https://www5.oab.org.br/integracao/Identidade.svc?WSDL")
public class Identidade
    extends Service
{

    private final static URL IDENTIDADE_WSDL_LOCATION;
    private final static WebServiceException IDENTIDADE_EXCEPTION;
    private final static QName IDENTIDADE_QNAME = new QName("https://www5.oab.org.br/integracao/", "Identidade");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www5.oab.org.br/integracao/Identidade.svc?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTIDADE_WSDL_LOCATION = url;
        IDENTIDADE_EXCEPTION = e;
    }

    public Identidade() {
        super(__getWsdlLocation(), IDENTIDADE_QNAME);
    }

    public Identidade(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTIDADE_QNAME, features);
    }

    public Identidade(URL wsdlLocation) {
        super(wsdlLocation, IDENTIDADE_QNAME);
    }

    public Identidade(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTIDADE_QNAME, features);
    }

    public Identidade(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Identidade(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IIdentidade
     */
    @WebEndpoint(name = "BasicHttpsBinding_IIdentidade")
    public IIdentidade getBasicHttpsBindingIIdentidade() {
        return super.getPort(new QName("https://www5.oab.org.br/integracao/", "BasicHttpsBinding_IIdentidade"), IIdentidade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IIdentidade
     */
    @WebEndpoint(name = "BasicHttpsBinding_IIdentidade")
    public IIdentidade getBasicHttpsBindingIIdentidade(WebServiceFeature... features) {
        return super.getPort(new QName("https://www5.oab.org.br/integracao/", "BasicHttpsBinding_IIdentidade"), IIdentidade.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTIDADE_EXCEPTION!= null) {
            throw IDENTIDADE_EXCEPTION;
        }
        return IDENTIDADE_WSDL_LOCATION;
    }

}
