
package com.dev.cna;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IIdentidade", targetNamespace = "https://www5.oab.org.br/integracao/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IIdentidade {


    /**
     * 
     * @param uf
     * @param inscricao
     * @param dataCompromisso
     * @param numeroPagina
     * @param cpf
     * @param nomeAdvogado
     * @return
     *     returns com.dev.cna.ArrayOfTOConsultaAdvogadoResult
     */
    @WebMethod(operationName = "ConsultaAdvogado", action = "https://www5.oab.org.br/integracao/IIdentidade/ConsultaAdvogado")
    @WebResult(name = "ConsultaAdvogadoResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "ConsultaAdvogado", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaAdvogado")
    @ResponseWrapper(localName = "ConsultaAdvogadoResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaAdvogadoResponse")
    public ArrayOfTOConsultaAdvogadoResult consultaAdvogado(
        @WebParam(name = "cpf", targetNamespace = "https://www5.oab.org.br/integracao/")
        String cpf,
        @WebParam(name = "inscricao", targetNamespace = "https://www5.oab.org.br/integracao/")
        String inscricao,
        @WebParam(name = "uf", targetNamespace = "https://www5.oab.org.br/integracao/")
        String uf,
        @WebParam(name = "nomeAdvogado", targetNamespace = "https://www5.oab.org.br/integracao/")
        String nomeAdvogado,
        @WebParam(name = "dataCompromisso", targetNamespace = "https://www5.oab.org.br/integracao/")
        XMLGregorianCalendar dataCompromisso,
        @WebParam(name = "numeroPagina", targetNamespace = "https://www5.oab.org.br/integracao/")
        Integer numeroPagina);

    /**
     * 
     * @param cpf
     * @return
     *     returns com.dev.cna.ArrayOfTOConsultaAdvogadoImagemResult
     */
    @WebMethod(operationName = "ConsultaAdvogadoImagem", action = "https://www5.oab.org.br/integracao/IIdentidade/ConsultaAdvogadoImagem")
    @WebResult(name = "ConsultaAdvogadoImagemResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "ConsultaAdvogadoImagem", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaAdvogadoImagem")
    @ResponseWrapper(localName = "ConsultaAdvogadoImagemResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaAdvogadoImagemResponse")
    public ArrayOfTOConsultaAdvogadoImagemResult consultaAdvogadoImagem(
        @WebParam(name = "cpf", targetNamespace = "https://www5.oab.org.br/integracao/")
        String cpf);

    /**
     * 
     * @param cpf
     * @return
     *     returns com.dev.cna.TOBiometricoAdvogado
     */
    @WebMethod(operationName = "ConsultaDadosBiometrico", action = "https://www5.oab.org.br/integracao/IIdentidade/ConsultaDadosBiometrico")
    @WebResult(name = "ConsultaDadosBiometricoResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "ConsultaDadosBiometrico", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaDadosBiometrico")
    @ResponseWrapper(localName = "ConsultaDadosBiometricoResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaDadosBiometricoResponse")
    public TOBiometricoAdvogado consultaDadosBiometrico(
        @WebParam(name = "cpf", targetNamespace = "https://www5.oab.org.br/integracao/")
        String cpf);

    /**
     * 
     * @param requerimento
     * @return
     *     returns com.dev.cna.ArrayOfTOConsultaPedidoResult
     */
    @WebMethod(operationName = "ConsultaPedido", action = "https://www5.oab.org.br/integracao/IIdentidade/ConsultaPedido")
    @WebResult(name = "ConsultaPedidoResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "ConsultaPedido", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaPedido")
    @ResponseWrapper(localName = "ConsultaPedidoResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaPedidoResponse")
    public ArrayOfTOConsultaPedidoResult consultaPedido(
        @WebParam(name = "requerimento", targetNamespace = "https://www5.oab.org.br/integracao/")
        String requerimento);

    /**
     * 
     * @param cpf
     * @return
     *     returns com.dev.cna.ArrayOfTOConsultaPedido
     */
    @WebMethod(operationName = "ConsultaPedidoCPF", action = "https://www5.oab.org.br/integracao/IIdentidade/ConsultaPedidoCPF")
    @WebResult(name = "ConsultaPedidoCPFResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "ConsultaPedidoCPF", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaPedidoCPF")
    @ResponseWrapper(localName = "ConsultaPedidoCPFResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaPedidoCPFResponse")
    public ArrayOfTOConsultaPedido consultaPedidoCPF(
        @WebParam(name = "cpf", targetNamespace = "https://www5.oab.org.br/integracao/")
        String cpf);

    /**
     * 
     * @param dadosAdvogado
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviaAdvogado", action = "https://www5.oab.org.br/integracao/IIdentidade/EnviaAdvogado")
    @WebResult(name = "EnviaAdvogadoResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "EnviaAdvogado", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.EnviaAdvogado")
    @ResponseWrapper(localName = "EnviaAdvogadoResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.EnviaAdvogadoResponse")
    public String enviaAdvogado(
        @WebParam(name = "dadosAdvogado", targetNamespace = "https://www5.oab.org.br/integracao/")
        TOEnviaAdvogado dadosAdvogado);

    /**
     * 
     * @param dadosPedido
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviaPedido", action = "https://www5.oab.org.br/integracao/IIdentidade/EnviaPedido")
    @WebResult(name = "EnviaPedidoResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "EnviaPedido", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.EnviaPedido")
    @ResponseWrapper(localName = "EnviaPedidoResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.EnviaPedidoResponse")
    public String enviaPedido(
        @WebParam(name = "dadosPedido", targetNamespace = "https://www5.oab.org.br/integracao/")
        TOEnviaPedido dadosPedido);

    /**
     * 
     * @param organizacao
     * @param organizacaoTransferencia
     * @param cpf
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviaTransferencia", action = "https://www5.oab.org.br/integracao/IIdentidade/EnviaTransferencia")
    @WebResult(name = "EnviaTransferenciaResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "EnviaTransferencia", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.EnviaTransferencia")
    @ResponseWrapper(localName = "EnviaTransferenciaResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.EnviaTransferenciaResponse")
    public String enviaTransferencia(
        @WebParam(name = "organizacao", targetNamespace = "https://www5.oab.org.br/integracao/")
        Integer organizacao,
        @WebParam(name = "cpf", targetNamespace = "https://www5.oab.org.br/integracao/")
        String cpf,
        @WebParam(name = "organizacaoTransferencia", targetNamespace = "https://www5.oab.org.br/integracao/")
        Integer organizacaoTransferencia);

    /**
     * 
     * @param tipoTransferencia
     * @param cpf
     * @return
     *     returns com.dev.cna.ArrayOfTOConsultaTransferenciaResult
     */
    @WebMethod(operationName = "ConsultaTransferencia", action = "https://www5.oab.org.br/integracao/IIdentidade/ConsultaTransferencia")
    @WebResult(name = "ConsultaTransferenciaResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "ConsultaTransferencia", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaTransferencia")
    @ResponseWrapper(localName = "ConsultaTransferenciaResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaTransferenciaResponse")
    public ArrayOfTOConsultaTransferenciaResult consultaTransferencia(
        @WebParam(name = "tipoTransferencia", targetNamespace = "https://www5.oab.org.br/integracao/")
        String tipoTransferencia,
        @WebParam(name = "cpf", targetNamespace = "https://www5.oab.org.br/integracao/")
        String cpf);

    /**
     * 
     * @param cpf
     * @return
     *     returns com.dev.cna.TOImpedimentoAdvogado
     */
    @WebMethod(operationName = "ConsultaImpedimentosDoAdvogado", action = "https://www5.oab.org.br/integracao/IIdentidade/ConsultaImpedimentosDoAdvogado")
    @WebResult(name = "ConsultaImpedimentosDoAdvogadoResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "ConsultaImpedimentosDoAdvogado", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaImpedimentosDoAdvogado")
    @ResponseWrapper(localName = "ConsultaImpedimentosDoAdvogadoResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.ConsultaImpedimentosDoAdvogadoResponse")
    public TOImpedimentoAdvogado consultaImpedimentosDoAdvogado(
        @WebParam(name = "cpf", targetNamespace = "https://www5.oab.org.br/integracao/")
        String cpf);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetIP", action = "https://www5.oab.org.br/integracao/IIdentidade/GetIP")
    @WebResult(name = "GetIPResult", targetNamespace = "https://www5.oab.org.br/integracao/")
    @RequestWrapper(localName = "GetIP", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.GetIP")
    @ResponseWrapper(localName = "GetIPResponse", targetNamespace = "https://www5.oab.org.br/integracao/", className = "com.dev.cna.GetIPResponse")
    public String getIP();

}
